// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhzxkjdllpfikmsvdpsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oenhramRsbHBmaWttc3ZkcHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDU2NzUsImV4cCI6MjA1ODEyMTY3NX0.5ek-uqts5dBoypkiYti-bZJMuewlY382nBpvJqx0Y5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);