// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzmrgvtxsffccpuqallc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bXJndnR4c2ZmY2NwdXFhbGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1MTEyNjgsImV4cCI6MjA1ODA4NzI2OH0.Tavbfl1QJ4xLCURyYHG9g4wiRuzt5OHilkhYhurFbWY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);